service: template-express
frameworkVersion: '3'

#custom:
#tableName: 'users-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs16.x
  region:  us-east-1 #us-west-2

functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*'
